// File generated by FlutterFire CLI.
// This file should be replaced with the one generated by running 'flutterfire configure'

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default FirebaseOptions for use with your Firebase apps.
///
/// IMPORTANT: This is a placeholder file. You need to generate the actual file:
///
/// 1. Install the FlutterFire CLI if you haven't already:
///    ```bash
///    dart pub global activate flutterfire_cli
///    ```
///
/// 2. Run the configure command at your project root:
///    ```bash
///    flutterfire configure
///    ```
///
/// 3. Follow the interactive prompts to select your Firebase project
///    and platforms.
///
/// 4. This will generate a proper firebase_options.dart file to replace this one.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you need to follow the setup instructions in the FIREBASE_SETUP.md file',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you need to follow the setup instructions in the FIREBASE_SETUP.md file',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkpJCzXEm_ObjVAQ1ebGjc4YnORh5YPFM',
    appId: '1:551251134392:android:15b476fa98edb57d81714d',
    messagingSenderId: '551251134392',
    projectId: 'capstone-diet-fitness',
    storageBucket: 'capstone-diet-fitness.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1xM9hLqjnaqagrVrhw9H-XaEOJlhrKOo',
    appId: '1:324176872162:web:948c23c299c26dee5094bb',
    messagingSenderId: '324176872162',
    projectId: 'capstone-7642f',
    authDomain: 'capstone-7642f.firebaseapp.com',
    storageBucket: 'capstone-7642f.firebasestorage.app',
    measurementId: 'G-4ZGBCXK115',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtTWHK9aCiBS047ortomSHp_mScfCxHH0',
    appId: '1:551251134392:ios:73253552db089f3881714d',
    messagingSenderId: '551251134392',
    projectId: 'capstone-diet-fitness',
    storageBucket: 'capstone-diet-fitness.firebasestorage.app',
    iosClientId: '551251134392-fak5k6tkjvvjlk91nr96k5j0lhv39b1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.attempt2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1xM9hLqjnaqagrVrhw9H-XaEOJlhrKOo',
    appId: '1:324176872162:web:1e4828ec3ff7e72b5094bb',
    messagingSenderId: '324176872162',
    projectId: 'capstone-7642f',
    authDomain: 'capstone-7642f.firebaseapp.com',
    storageBucket: 'capstone-7642f.firebasestorage.app',
    measurementId: 'G-DXVWKR9NWH',
  );

}